project:
  type: website

website:
  title: "quarto-pub"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tes2.ipynb
        text: tes2

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



