project:
  type: website

website:
  title: "Wakatta"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tes3.qmd
        text: tes3
      - href: loadmap.qmd
        text: Loadmap 
      - href: tes-obs.qmd
        text: Observals101 
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



