project:
  type: website

website:
  title: "quarto-pub"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tes3.qmd
        text: tes3
      - href: loadmap.qmd
        text: Loadmap 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



